travis:
  secure:
    BINSTAR_TOKEN: v/+OuOAWrGtQRJKtXdFDsf9A1hATD+aSJxe4GpXzCArBh4hgMGA2JHIdneV6WI/CT2CGF/rOUtulEaPj8BHgwmC3Umu12YwcTjHbtS/2FO0QeDsRxPzgFsRpZf6LEQORMfpBUbCmjiSFosBWNvHZpS9fLagjRcQSJ3HgUHADLGvPc0NztQbvh3UaezZIj529xOGhY4laAbIufHB3CCliBcFYMrSywjrd5fj2l+ZZAXUYTMt4vEDSfGRHI0HTHo6jvDUP3b+g9wAQSPjlXiyGcpy8lcPkwzMgwizJflIOCMIuvEovctg28LCrNFToh2fODfPXTaejfWUnjN1daIM5w2LIk+t+5UUNeOVss1UfzUb99veHrMjprC8OkSgw9i9dwd4O9CmE0lIDNquzRC3EOxxC3NJbvV81JTSQ6IbrRFb3LHIhb8xy62L1VqzqEPAnxsW3pAixCjgHtxWASxkbjSUtNf+7fpDhpsvRW+RxHwtJdMFP1fieOO+9iCCeCjvCxfQB9/OoY+jbT5XmzNkbopW1saJ6k5zYoTj5oHdxjIVroYzhh/H5K4/U3cyD0m6oX/7UJLZh51HE2/Iw6Gn+rGbTEGfLkgabJwx9apFsVONSnHEsQy5jijFRd7ETL+4UEL5f5LIMK3PpqrCFhaYJLlpotLjJFnBl5/NenfDHARw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
